# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 02039d183d746f1d8079f141abc1c627c23c2592c48c66adfb3bbb4af68b8b259e4c93e376cfef3be3618b9fe9f278c905f1428dc0ce00444c4fba5596afcb02

test:
  secret_key_base: 06935555417f62966cea68eec3b709aaf637af0189e1e7713127671a3a246a9e53fa7f814338915eee672e3dcdd7b7d2b2bd976ec0a15f018857a60769df6f05

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
